-- AlterTable
ALTER TABLE `notifikasis` MODIFY `jenis` ENUM('TENANT_BARU', 'TAGIHAN', 'KEAMANAN', 'LAPORAN', 'PELANGGARAN', 'KESEHATAN', 'PERIZINAN', 'NILAI', 'ABSENSI', 'SISTEM', 'DARURAT', 'WALI_BELUM_AKTIVASI') NOT NULL;
