-- AlterTable
ALTER TABLE `notifikasis` MODIFY `tenantId` VARCHAR(191) NULL,
    MODIFY `jenis` ENUM('TENANT_BARU', 'TAGIHAN', 'KEAMANAN', 'LAPORAN', 'PELANGGARAN', 'KESEHATAN', 'PERIZINAN', 'NILAI', 'ABSENSI', 'SISTEM', 'DARURAT') NOT NULL;
